
TAG_FALLACY  = u"TAGFALLACY";
TAG_CLINCHER = u"TAGCLINCHER";
TAG_IAGREE = u"TAGIAGREE";
TAG_POSITIVE = u"TAG_POSITIVE";
TAG_OP = u"TAG_OP";
TAG_VIEWER = u"TAG_VIEWER";
TAG_VIEWEROP = u"TAG_VIEWEROP";
TAG_SYS = u"TAG_SYS";



sharedprefs = u"sharedpreferences";
NOTIFICATION_CHANNEL_ID = u"vitandachannelid";

CLINCHER_NONE = u"";
CLINCHER_SHIFT_PRO = u"Shifting the Proposition";
CLINCHER_OPP_PRO =   "Opposing the Proposition";
CLINCHER_SHIFT_TOP = u"Shifting Topic";
CLINCHER_INCOHERENT ="Incoherent";
CLINCHER_SAYING_LIT ="Saying too Little";
CLINCHER_REPEAT =    "Repetition";
CLINCHER_CONTRA_ST = u"Contradiction to Stand";
CLINCHER_OBSTINACY = u"Obstinacy";


FALLACY_NONE = u"";
FALLACY_ERRATIC = u"Erratic Reasoning";
FALLACY_SHIFT_REA = u"Shifting the Reason";
FALLACY_UNINTELLI = u"Unintelligible";
FALLACY_SHAKY_FOU = u"Shaky Foundation";
FALLACY_FAR_FETCH = u"Far fetched Analogy";
FALLACY_QUIBBLE_T = u"Quibbling on the Term";
FALLACY_QUIBBLE_M = u"Qubbling on the Metaphor";
FALLACY_ATTACK_WS = u"Attack witout substance";

POSITIVE_NONE = u"POSITIVE_NONE";
POSITIVE_IAGREE = u"#IAgree";

TAGOP_NONE = u"TAGOP_NONE";
TAGOP_IACCEPT = u"#IAccept";
TAGOP_IREJECT = u"#IReject";

SYSTAG_DEADLOCK = u"#Deadlock";
TAGOP_INVITEMOD = u"#InviteaModerator";
TAGOP_IASKGURU = u"#IAskGuru";

TAGOP_MODIACCEPTASGURU = u"#IAcceptasGuru";
TAGOP_MODIREJECTASGURU = u"#IRejectasGuru";



PA_NONE = u"";
PA_AGREEMENT = u"We're in Agreement";


ACTION_CLARI = u"Clarification";
ACTION_REQ_IS = u"Request Information Source";
ACTION_LIST_CL = u"List Claim";
ACTION_SEEK_IN = u"Seek Intervention";

VIWERAC_PLUSONE = u"plusone";
VIWERAC_REPLY = u"reply";
VIWERAC_NEEDSOURCE = u"needsource";
VIWERAC_SUBJECTIVE = u"subjective";
VIWERAC_RELEVENCE = u"relevance";
VIWERAC_EXCELLENT = u"excellence";
VIWERAC_UPGRADE = u"upgrade";
VIWERAC_LACKREASON = u"lacksreason";
VIWERAC_LACKSEXAMP = u"lacks example";

TURN_FOR = u"FOR";
TURN_AG = u"AGAINST";
TURN_MOD = u"MODERATOR";

ARGTYPE_ASSRT = u"ASSERT";

MESSAGES_CHILD = u"messages";

MESSAGE_URL = u"http://friendlychat.firebase.google.com/message/";
LOADING_IMAGE_URL = u"https://www.google.com/images/spin-32.gif";
REQUEST_INVITE = 1;
REQUEST_IMAGE = 2;

DEFAULT_MSG_LENGTH_LIMIT = 10;
ANONYMOUS = u"anonymous";
MESSAGE_SENT_EVENT = u"message_sent";

FB_RCOLL_DEBATES = u"debates";
FB_RCOLL_USERSBYUID = u"usersbyuid";
FB_RCOLL_USERSBYSID = u"usersbysid";
FB_RCOLL_SIDLIST = u"sidlist";
FB_RCOLL_MYPARTICIPATION = u"MYPARTICIPATION";

FB_COLL_CONVS = u"convs";
FB_COLL_KEYARGS = u"keyargs";
FB_COLL_MYDEBATES = u"MYDEBATES";
FB_COLL_MYINVITES = u"MYINVITES";



ARGOP_FALLACY = u"sendfallacy";
ARGOP_CLINCHER = u"sendclincher";
ARGOP_MESSAGE = u"sendmessage";
ARGOP_IAGREE = u"sendiagree";


DEBACTIVSTATE_WAITINGJOIN = u"Waiting to Start";
DEBACTIVSTATE_ONGOING = u"Ongoing";
DEBACTIVSTATE_WAITINGASSESS = u"Waiting Assessment";
DEBACTIVSTATE_FINISHED = u"Finished";


TAG_ACCEPTED = u"TAGACCEPTED";
TAG_REJECTED = u"TAG_REJECTED";
TAG_PENDING = u"TAG_PENDING";
TAG_NONE = u"TAG_NONE";

VIEW_NOMSG = 0;
VIEW_RIGHTMSG = 1;
VIEW_LEFTMSG = 2;
VIEW_MODERATORMSG = 3;
VIEW_SYSMSG = 4;
VIEW_SYSMSG_DEBEND = 5;

MSGTYPE_DEB = u"DEB";
MSGTYPE_MOD = u"MOD";
MSGTYPE_SYS = u"SYS";
MSGTYPE_SYS_DEBEND = u"SYSDEBEND";
MSGTYPE_NONE = u"NONE";

TILT_NONE = u"NONE";
TILT_FOR = u"FOR";
TILT_AG = u"AGAINST";
TILT_MOD = u"MODERATOR";
TILT_SYS = u"SYS";

ARG_ROLE_DEB = u"DEBATER";
ARG_ROLE_MOD = u"MODERATOR";
ARG_ROLE_VIEW = u"VIEWER";
ARG_ROLE_NONE = u"NONE";


MAX_KEYARGCOUNT = 2;
MAX_POINTSPERBOUT = 2;
MAX_BOUTSPERCONV = 2;
MAX_FALLCIESPERCLINCHER = 2;
ONEFALLACY = 1;

MYDEB_MEASMOD = 1;
MYDEB_MEASDEB = 2;
MYDEB_NOTMEASMOD = 3;
MYDEB_NOTMEASDEB = 4;
